'use strict';

import type { NestedStringRecord } from "../utils/Utils.ts";

const DEFAULT_LANGUAGE: NestedStringRecord = {
    calendar: {
        dateOrder: 'MDY',
        dayNames: {
            full: [
                'Sunday',
                'Monday',
                'Tuesday',
                'Wednesday',
                'Thursday',
                'Friday',
                'Saturday'
            ],
            short: [
                'Sun',
                'Mon',
                'Tue',
                'Wed',
                'Thu',
                'Fri',
                'Sat'
            ]
        },
        numberSuffixes: [
            'st',
            'nd',
            'rd',
            'th'
        ],
        months: {
            full: [
                'January',
                'February',
                'March',
                'April',
                'May',
                'June',
                'July',
                'August',
                'September',
                'October',
                'November',
                'December'
            ],
            short: [
                'Jan',
                'Feb',
                'Mar',
                'Apr',
                'May',
                'Jun',
                'Jul',
                'Aug',
                'Sep',
                'Oct',
                'Nov',
                'Dec'
            ]
        }
    },
    errors: {
        array: {
            base: 'Must be an array', //todo:check
            allOf: 'Must contain all of these values: {requiredValues}, missing: {missingValue}',
            dimensions: 'Must have dimensions {dimensions}',
            empty: 'Must be empty, current length: {length}',
            exactly: 'Must contain exactly these values: {requiredValues}',
            length: 'Must have a length of {requiredLength}, Current length: {length}',
            lengthBetween: 'Must have a length between {min} and {max}, Current length: {length}',
            maxLength: 'Must contain more than {max} items, Current length: {length}',
            minLength: 'Must contain less than {min} items, Current length: {length}',
            noneOf: 'Cannot contain any of these values: {forbiddenValues}, found {invalidValue} at index {index}',
            notEmpty: 'Must not be empty',
            only: 'Can only contain values from: {allowedValues}. Invalid value {invalidValue} found at index {index}',
            otherThan: 'Cannot contain any of these values: {forbiddenValues}, found {invalidValue} at index {index}',
            someOf: 'Must contain at least one of these values: {possibleValues}',
            sorted: 'Must be sorted, first unsorted value {invalidValue} found at index {index}',
            tuple: 'Must match the tuple values: {tupleValues}, expected {expectedValue} at index {index}, but found {invalidValue}',
            unique: 'Must contain only unique values, duplicate value {duplicateValue} found at indices {index1} and {index2}',
        },
        boolean: {
            base: 'Must be a boolean value (true/false)',
            truthy: 'Must be true or one of the truthy values: {truthyValues}',
            falsy: 'Must be false or one of the falsy values: {falsyValues}',
            invert: 'Must be a boolean value that can be inverted with the provided boolish pairs: {boolishPairs}',
        },
        date: {
            base: 'Must be a valid date',
            addDays: 'Days must be an integer',
            addHours: 'Hours must be an integer',
            addMinutes: 'Minutes must be an integer',
            addMonths: 'Months must be an integer',
            addYears: 'Years must be an integer',
            after: 'Must be after {afterDate}',
            before: 'Must be before {beforeDate}',
            between: 'Must be between {minDate} and {maxDate}',
            dayOfWeek: 'Must be day of week {dayOfWeek}',
            equals: 'Must equal {compareDate}',
            future: 'Must be in the future',
            human: 'Must be a valid human-readable date format',
            iso: 'Must be a valid ISO date format',
            isoOrdinal: 'Must be a valid ISO ordinal date format',
            isoWeek: 'Must be a valid ISO week date format',
            leapYear: 'Must be in a leap year',
            max: 'Must be before or equal to {maxDate}',
            min: 'Must be after or equal to {compareDate}',
            minAge: 'Must be at least {minAge} years old',
            past: 'Must be in the past',
            recent: 'Must be within the last {days} days',
            timestamp: 'Must be a valid timestamp',
            today: 'Must be today',
            toNextDayOfWeek: 'Target day must be between 0 and 6',
            weekday: 'Must be a weekday',
            weekend: 'Must be a weekend',
        },
        generic: {
            defined: 'Must be defined',
            empty: 'Must be empty',
            equals: 'Must equal {comparison}',
            falsy: 'Must be falsy',
            forbidden: 'Field is forbidden',
            format: 'Invalid format',
            notDefined: 'Must be undefined',
            notEmpty: 'Must not be empty',
            notEquals: 'Must not equal {comparison}',
            notNull: 'Must not be null',
            notOneOf: 'Cannot be one of: {forbiddenValues}',
            null: 'Must be null',
            oneOf: 'Must be one of: {allowedValues}',
            primitive: 'Must be a primitive type',
            required: 'Field is required',
            truthy: 'Must be truthy',
        },
        number: {
            base: 'Must be a number',
            approx: 'Must be approximately equal to {comparison} (tolerance: {tolerance})',
            between: 'Must be between {min} and {max}',
            decimal: 'Must be a decimal with between {minDecimalPlaces} and {maxDecimalPlaces} decimal places',
            equals: 'Must equal {comparison}',
            even: 'Must be an even number',
            factor: 'Must be a factor of {multiple}',
            finite: 'Must be a finite number',
            greaterThan: 'Must be greater than {comparison}',
            infinity: 'Must be Infinity or -Infinity',
            integer: 'Must be an integer',
            lessThan: 'Must be less than {comparison}',
            max: 'Must be less than or equal to {comparison}',
            min: 'Must be greater than or equal to {comparison}',
            minusSign: 'Must include a minus sign',
            multiple: 'Must be a multiple of {factor}',
            negative: 'Must be a negative number',
            notEquals: 'Must not equal {comparison}',
            odd: 'Must be an odd number',
            plusSign: 'Must include a plus sign',
            positive: 'Must be a positive number',
            precision: 'Must have precision of {precision} decimal places',
            prime: 'Must be a prime number',
            safe: 'Must be within JavaScript safe integer range',
            safeInteger: 'Must be a safe integer',
            signed: 'Must include a sign (+ or -)',
            unsigned: 'Must be unsigned (found sign: {sign})',
            zero: 'Must be zero',
        },
        object: {
            base: 'Must be an object',
            allOfButXOfPaths: 'Must contain all of these paths except {count}: {paths}',
            allOfPaths: 'Must contain all required paths, missing: {missingPaths}',
            depth: 'Must have depth {depth}, actual depth: {actualDepth}',
            empty: 'Must be an empty object',
            ensurePlain: 'Must be a plain object',
            exactlyPaths: 'Must contain exactly these paths: {paths}',
            instanceOf: 'Must be an instance of {constructor}',
            isObject: 'Must be an object',
            keyCount: 'Must have exactly {keyCount} keys, actual: {actualKeyCount}',
            keyCountRecursive: 'Must have exactly {keyCount} keys recursively, actual: {actualKeyCount}',
            maxDepth: 'Must have depth at most {maxDepth}, actual depth: {actualDepth}',
            maxKeyCount: 'Must have at most {maxKeyCount} keys, actual: {actualKeyCount}',
            maxKeyCountRecursive: 'Must have at most {maxKeyCount} keys recursively, actual: {actualKeyCount}',
            minDepth: 'Must have depth at least {minDepth}, actual depth: {actualDepth}',
            minKeyCount: 'Must have at least {minKeyCount} keys, actual: {actualKeyCount}',
            minKeyCountRecursive: 'Must have at least {minKeyCount} keys recursively, actual: {actualKeyCount}',
            noneOfPaths: 'Must not contain any of these paths: {paths}',
            notEmpty: 'Must not be empty',
            onlyPaths: 'Must contain only these paths: {paths}',
            pathsOtherThan: 'Must contain paths other than: {paths}',
            plain: 'Must be a plain object',
            property: 'Must include property {property}',
            recursion: {
                tooDeep: 'Recursive structure exceeds maximum depth',
                tooShallow: 'Recursive structure does not meet minimum depth',
            },
            someOfPaths: 'Must contain at least one of these paths: {paths}',
            tooComplex: 'Object is too complex (max depth: {maxDepth}, max keys: {maxKeyCount})',
            xOfPaths: 'Must contain exactly {count} of these paths: {paths}',
        },
        string: {
            base: 'Must be a string',
            alpha: 'Must contain only letters',
            alphanumeric: 'Must contain only letters and numbers',
            ascii: 'Must contain only ASCII characters',
            balanced: {
                positive: 'Must have balanced {openChar} and {closeChar} characters (remaining open count: {openCount})',
                negative: 'Unexpected closing {closeChar} before matching {openChar} at position {index}',
            },
            base64: 'Must be a valid base64 string',
            base64Decode: 'Unable to decode base64 string',
            base64Encode: 'Unable to encode string to base64',
            binary: 'Must be a valid binary string',
            bmp: 'Must contain only BMP unicode characters',
            complex: {
                digits: 'Must meet minimum digit count of {minDigits}',
                length: 'Must be between {minLen} and {maxLen} characters long',
                uppercase: 'Must contain at least {minUppercase} uppercase letter(s)',
                lowercase: 'Must contain at least {minLowercase} lowercase letter(s)',
                specialChars: 'Must contain at least {minSpecialChars} special character(s)',
                repeats: 'Cannot have more than {maxRepeats} consecutive identical characters',
            },
            contains: 'Must contain {substring}',
            creditCard: 'Must be a valid credit card number',
            currencyCode: 'Must be a valid ISO currency code',
            dataUrl: 'Must be a valid data URL',
            digits: 'Must contain only digits',
            domain: 'Must be a valid domain',
            e164: 'Must be a valid E.164 phone number',
            email: 'Must be a valid email address',
            empty: 'Must be empty',
            endsWith: 'Must end with {suffix}',
            excludesChars: 'Must not contain any of these characters: {chars}',
            gtin: 'Must be a valid GTIN',
            hash: 'Must be a valid {algorithm} hash',
            hex: 'Must be a valid hexadecimal string',
            hexColor: 'Must be a valid hex color',
            imei: 'Must be a valid IMEI',
            ip: 'Must be a valid IP address',
            ipCidr: 'Must be a valid CIDR',
            ipCidrV4: 'Must be a valid IPv4 CIDR',
            ipCidrV6: 'Must be a valid IPv6 CIDR',
            ipV4: 'Must be a valid IPv4 address',
            ipV6: 'Must be a valid IPv6 address',
            json: 'Must be valid JSON',
            jwt: 'Must be a valid JWT',
            label: 'Must be a valid label',
            length: 'Must have length {length}',
            lengthBetween: 'Must have length between {min} and {max}',
            lowerCase: 'Must be lowercase',
            luhn: 'Must pass the Luhn check',
            mac: 'Must be a valid MAC address',
            matches: 'Must match regex {regex}',
            maxLength: 'Must have length at most {max}',
            maxWords: 'Must have at most {max} words, actual: {count}',
            measurement: 'Must be a valid measurement',
            minLength: 'Must have length at least {min}',
            minWords: 'Must have at least {min} words, actual: {count}',
            money: 'Must be a valid monetary value',
            notEmpty: 'Must not be empty',
            numeric: {
                base: 'Must be a valid numeric string',
                missingSign: 'Sign must be on the configured side of the number',
                missingPlusSign: 'Must include a plus sign',
                missingMinusSign: 'Must include a minus sign',
                forbiddenMinusSign: 'Minus sign is not allowed',
                forbiddenDecimal: 'Decimal part is not allowed',
                missingDecimal: 'Must include a decimal part',
                invalidIntegral: 'Integral part is invalid',
                forbiddenLeadingZero: 'Leading zero is not allowed',
                invalidFractional: 'Fractional part is invalid',
                missingTrailingZero: 'Must include trailing decimal digits',
                forbiddenTrailingZero: 'Trailing zero is not allowed',
                min: 'Must be greater than or equal to {min}',
                max: 'Must be less than or equal to {max}',
            },
            octal: 'Must be a valid octal string',
            onlyChars: 'Must contain only these characters: {chars}',
            path: 'Must be a valid path',
            phone: 'Must be a valid phone number',
            repetition: 'Must contain fragment {fragment} between {min} and {max} times',
            slug: 'Must be a valid slug',
            ssn: 'Must be a valid SSN',
            startsWith: 'Must start with {prefix}',
            state: 'Must be a valid state code',
            upperCase: 'Must be uppercase',
            url: 'Must be a valid URL',
            uuid: 'Must be a valid UUID',
            wordCount: 'Must have between {min} and {max} words, actual: {count}',
            zip: {
                base: 'Must be a valid ZIP code',
                required4: 'Must include ZIP+4 extension',
                forbidden4: 'ZIP+4 extension is not allowed',
            },
        }
    }
};

export { DEFAULT_LANGUAGE };