'use strict';

const DefaultErrorText: Record<string, string> = {
    'array/base': 'Must be an array',
    'array/allOf': 'Must contain all of these values: {requiredValues}, missing: {missingValue}',
    'array/dimensions': 'Must have dimensions {dimensions}',
    'array/empty': 'Must be empty, current length: {length}',
    'array/exactly': 'Must contain exactly these values: {requiredValues}',
    'array/length': 'Must have a length of {requiredLength}, Current length: {length}',
    'array/lengthBetween': 'Must have a length between {min} and {max}, Current length: {length}',
    'array/maxLength': 'Must contain at most {max} items, Current length: {length}',
    'array/minLength': 'Must contain at least {min} items, Current length: {length}',
    'array/noneOf': 'Cannot contain any of these values: {forbiddenValues}, found {invalidValue} at index {index}',
    'array/notEmpty': 'Must not be empty',
    'array/only': 'Can only contain values from: {allowedValues}. Invalid value {invalidValue} found at index {index}',
    'array/otherThan': 'Must contain at least one value other than: {forbiddenValues}',
    'array/anyOf': 'Must contain at least one of these values: {possibleValues}',
    'array/sorted': 'Must be sorted, first unsorted value {invalidValue} found at index {index}',
    'array/tuple': 'Must match the tuple values: {tupleValues}, expected {expectedValue} at index {index}, but found {invalidValue}',
    'array/unique': 'Must contain only unique values, duplicate value {duplicateValue} found at indices {index1} and {index2}',
    'boolean/base': 'Must be a boolean value (true/false)',
    'boolean/truthy': 'Must be true or one of the truthy values: {truthyValues}',
    'boolean/falsy': 'Must be false or one of the falsy values: {falsyValues}',
    'boolean/invert': 'Must be a boolean value that can be inverted with the provided boolish pairs: {boolishPairs}',
    'date/base': 'Must be a valid date',
    'date/addDays': 'Days must be an integer',
    'date/addHours': 'Hours must be an integer',
    'date/addMinutes': 'Minutes must be an integer',
    'date/addMonths': 'Months must be an integer',
    'date/addYears': 'Years must be an integer',
    'date/after': 'Must be after {referenceDate}',
    'date/before': 'Must be before {referenceDate}',
    'date/between': 'Must be between {minDate} and {maxDate}',
    'date/dayOfWeek': 'Must be day of week {dayOfWeek}',
    'date/equals': 'Must equal {referenceDate}',
    'date/future': 'Must be in the future',
    'date/human': 'Must be a valid human-readable date format (options: {options})',
    'date/iso': 'Must be a valid ISO date format (options: {options})',
    'date/isoOrdinal': 'Must be a valid ISO ordinal date format (options: {options})',
    'date/isoWeek': 'Must be a valid ISO week date format (options: {options})',
    'date/leapYear': 'Must be in a leap year',
    'date/max': 'Must be before or equal to {referenceDate}',
    'date/min': 'Must be after or equal to {referenceDate}',
    'date/minAge': 'Must be at least {minAge} years old, actual age: {actualAge}',
    'date/notEquals': 'Must not equal {referenceDate}',
    'date/past': 'Must be in the past',
    'date/sameDay': 'Must be on the same day as {referenceDate}',
    'date/sameMonth': 'Must be in the same month as {referenceDate}',
    'date/sameWeek': 'Must be in the same week as {referenceDate} (first day of week: {firstDayOfWeek})',
    'date/sameYear': 'Must be in the same year as {referenceDate}',
    'date/timestamp': 'Must be a valid timestamp (options: {options})',
    'date/today': 'Must be the same day as today ({referenceDate})',
    'date/toNextDayOfWeek': 'Target day must be between 0 and 6',
    'date/weekday': 'Must be a weekday (received day index: {dayOfWeek})',
    'date/weekend': 'Must be a weekend (received day index: {dayOfWeek})',
    'date/within': 'Must be within the last {daysDiff} days, current difference: {actualDiff} days',
    'any/anyOf': 'Must be one of: {allowedValues}',
    'any/defined': 'Must be defined',
    'any/empty': 'Must be empty',
    'any/equals': 'Must equal {comparison}',
    'any/falsy': 'Must be falsy',
    'any/instanceOf': 'Must be an instance of {constructor}',
    'any/noneOf': 'Cannot be one of: {forbiddenValues}',
    'any/notEmpty': 'Must not be empty',
    'any/notEquals': 'Must not equal {comparison}',
    'any/notNull': 'Must not be null',
    'any/notNullish': 'Must not be null or undefined',
    'any/null': 'Must be null',
    'any/nullish': 'Must be null or undefined',
    'any/primitive': 'Must be a primitive type (actual type: {actualType})',
    'any/truthy': 'Must be truthy',
    'any/undefined': 'Must be undefined',
    'number/base': 'Must be a number',
    'number/approx': 'Must be approximately equal to {comparison} (tolerance: {tolerance})',
    'number/between': 'Must be between {min} and {max}',
    'number/decimal': 'Must be a decimal; decimal places must be between {minDecimalPlaces} and {maxDecimalPlaces}',
    'number/equals': 'Must equal {comparison}',
    'number/even': 'Must be an even number',
    'number/factor': 'Must be a factor of {multiple}',
    'number/finite': 'Must be a finite number',
    'number/greaterThan': 'Must be greater than {comparison}',
    'number/infinity': 'Must be Infinity or -Infinity',
    'number/integer': 'Must be an integer',
    'number/lessThan': 'Must be less than {comparison}',
    'number/max': 'Must be less than or equal to {comparison}',
    'number/min': 'Must be greater than or equal to {comparison}',
    'number/minusSign': 'Must include a minus sign',
    'number/multiple': 'Must be a multiple of {factor}',
    'number/negative': 'Must be a negative number',
    'number/notEquals': 'Must not equal {comparison}',
    'number/odd': 'Must be an odd number',
    'number/plusSign': 'Must include a plus sign',
    'number/positive': 'Must be a positive number',
    'number/precision': 'Must have precision of {precision} decimal places',
    'number/prime': 'Must be a prime number',
    'number/safe': 'Must be within JavaScript safe integer range',
    'number/safeInteger': 'Must be a safe integer',
    'number/signed': 'Must include a sign (+ or -)',
    'number/unsigned': 'Must be unsigned (found sign: {sign})',
    'number/zero': 'Must be zero',
    'object/base': 'Must be an object',
    'object/allOfButXOfPaths': 'Must contain all of these paths except {count}: {paths}',
    'object/allOfPaths': 'Must contain all required paths, missing: {missingPaths}',
    'object/depth': 'Must have depth {depth}, actual depth: {actualDepth}',
    'object/empty': 'Must be an empty object',
    'object/ensurePlain': 'Must be a plain object',
    'object/exactlyPaths': 'Must contain exactly these paths: {paths}',
    'object/instanceOf': 'Must be an instance of {constructor}',
    'object/isObject': 'Must be an object',
    'object/keyCount': 'Must have exactly {keyCount} keys, actual: {actualKeyCount}',
    'object/keyCountRecursive': 'Must have exactly {keyCount} keys recursively, actual: {actualKeyCount}',
    'object/maxDepth': 'Must have depth at most {maxDepth}, actual depth: {actualDepth}',
    'object/maxKeyCount': 'Must have at most {maxKeyCount} keys, actual: {actualKeyCount}',
    'object/maxKeyCountRecursive': 'Must have at most {maxKeyCount} keys recursively, actual: {actualKeyCount}',
    'object/minDepth': 'Must have depth at least {minDepth}, actual depth: {actualDepth}',
    'object/minKeyCount': 'Must have at least {minKeyCount} keys, actual: {actualKeyCount}',
    'object/minKeyCountRecursive': 'Must have at least {minKeyCount} keys recursively, actual: {actualKeyCount}',
    'object/noneOfPaths': 'Must not contain any of these paths: {paths}',
    'object/notEmpty': 'Must not be empty',
    'object/onlyPaths': 'Must contain only these paths: {paths}',
    'object/pathsOtherThan': 'Must contain paths other than: {paths}',
    'object/plain': 'Must be a plain object',
    'object/property': 'Must include property {property}',
    'object/recursion/tooDeep': 'Recursive structure exceeds maximum depth',
    'object/recursion/tooShallow': 'Recursive structure does not meet minimum depth',
    'object/someOfPaths': 'Must contain at least one of these paths: {paths}',
    'object/tooComplex': 'Object is too complex (max depth: {maxDepth}, max keys: {maxKeyCount})',
    'object/xOfPaths': 'Must contain exactly {count} of these paths: {paths}',
    'string/base': 'Must be a string',
    'string/alpha': 'Must contain only letters',
    'string/alphanumeric': 'Must contain only letters and numbers',
    'string/ascii': 'Must contain only ASCII characters',
    'string/balanced/positive': 'Must have balanced {openChar} and {closeChar} characters (remaining open count: {openCount})',
    'string/balanced/negative': 'Unexpected closing {closeChar} before matching {openChar} at position {index}',
    'string/base64': 'Must be a valid base64 string',
    'string/base64Decode': 'Unable to decode base64 string',
    'string/base64Encode': 'Unable to encode string to base64',
    'string/binary': 'Must be a valid binary string',
    'string/blank': 'Must contain only whitespace characters',
    'string/bmp': 'Must contain only BMP unicode characters',
    'string/complex/digits': 'Must meet minimum digit count of {minDigits}',
    'string/complex/length': 'Must be between {minLen} and {maxLen} characters long',
    'string/complex/uppercase': 'Must contain at least {minUppercase} uppercase letter(s)',
    'string/complex/lowercase': 'Must contain at least {minLowercase} lowercase letter(s)',
    'string/complex/specialChars': 'Must contain at least {minSpecialChars} special character(s)',
    'string/complex/repeats': 'Cannot have more than {maxRepeats} consecutive identical characters',
    'string/contains': 'Must contain {substring}',
    'string/creditCard': 'Must be a valid credit card number',
    'string/currencyCode': 'Must be a valid ISO currency code',
    'string/dataUrl': 'Must be a valid data URL',
    'string/digits': 'Must contain only digits',
    'string/domain': 'Must be a valid domain',
    'string/e123': 'Must be a valid E.123 phone number',
    'string/e164': 'Must be a valid E.164 phone number',
    'string/email': 'Must be a valid email address',
    'string/empty': 'Must be empty',
    'string/endsWith': 'Must end with {suffix}',
    'string/excludesChars': 'Must not contain any of these characters: {chars}',
    'string/gtin': 'Must be a valid GTIN',
    'string/hash': 'Must be a valid {algorithm} hash',
    'string/hex': 'Must be a valid hexadecimal string',
    'string/hexColor': 'Must be a valid hex color',
    'string/imei': 'Must be a valid IMEI',
    'string/ip': 'Must be a valid IP address',
    'string/ipCidr': 'Must be a valid CIDR',
    'string/ipCidrV4': 'Must be a valid IPv4 CIDR',
    'string/ipCidrV6': 'Must be a valid IPv6 CIDR',
    'string/ipV4': 'Must be a valid IPv4 address',
    'string/ipV6': 'Must be a valid IPv6 address',
    'string/json': 'Must be valid JSON',
    'string/jwt': 'Must be a valid JWT',
    'string/label': 'Must be a valid label',
    'string/length': 'Must have length {length}',
    'string/lengthBetween': 'Must have length between {min} and {max}',
    'string/lowerCase': 'Must be lowercase',
    'string/luhn': 'Must pass the Luhn check',
    'string/mac': 'Must be a valid MAC address',
    'string/matches': 'Must match regex {regex}',
    'string/maxLength': 'Must have length at most {max}',
    'string/maxWords': 'Must have at most {max} words, actual: {count}',
    'string/measurement': 'Must be a valid measurement',
    'string/minLength': 'Must have length at least {min}',
    'string/minWords': 'Must have at least {min} words, actual: {count}',
    'string/money': 'Must be a valid monetary value',
    'string/notBlank': 'Must not be blank',
    'string/notEmpty': 'Must not be empty',
    'string/numeric/base': 'Must be a valid numeric string',
    'string/numeric/missingSign': 'Sign must be on the {alignment} side of the number',
    'string/numeric/missingPlusSign': 'Must include a plus sign',
    'string/numeric/missingMinusSign': 'Must include a minus sign',
    'string/numeric/forbiddenMinusSign': 'Minus sign is not allowed',
    'string/numeric/forbiddenPlusSign': 'Plus sign is not allowed',
    'string/numeric/forbiddenDecimal': 'Decimal part is not allowed',
    'string/numeric/missingDecimal': 'Must include a decimal part',
    'string/numeric/invalidDecimal': 'Contains too many decimal separators (configured decimal delimiter: {decimalDelim})',
    'string/numeric/invalidIntegral': 'Integral part is invalid',
    'string/numeric/missingLeadingZero': 'Must include a leading zero before the decimal part',
    'string/numeric/forbiddenLeadingZero': 'Leading zero is not allowed',
    'string/numeric/invalidFractional': 'Fractional part is invalid',
    'string/numeric/missingTrailingZero': 'Must include trailing decimal digits',
    'string/numeric/forbiddenTrailingZero': 'Trailing zero is not allowed',
    'string/numeric/min': 'Must be greater than or equal to {min}',
    'string/numeric/max': 'Must be less than or equal to {max}',
    'string/octal': 'Must be a valid octal string',
    'string/onlyChars': 'Must contain only these characters: {chars}',
    'string/path': 'Must be a valid path',
    'string/phone': 'Must be a valid phone number',
    'string/repeats': 'Must contain fragment {fragment} between {min} and {max} times',
    'string/slug': 'Must be a valid slug',
    'string/ssn': 'Must be a valid SSN',
    'string/startsWith': 'Must start with {prefix}',
    'string/state': 'Must be a valid state code',
    'string/upperCase': 'Must be uppercase',
    'string/url': 'Must be a valid URL',
    'string/uuid': 'Must be a valid UUID',
    'string/wordCount': 'Must have between {min} and {max} words, actual: {count}',
    'string/zip/base': 'Must be a valid ZIP code',
    'string/zip/required4': 'Must include ZIP+4 extension',
    'string/zip/forbidden4': 'ZIP+4 extension is not allowed',
};

export { DefaultErrorText };